# .github/workflows/sync-labels.yml
name: "🔖 Sincronizar etiquetas"

on:
  workflow_dispatch:

permissions:
  issues: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sincronizar etiquetas con gh CLI
        run: |
          cat <<EOF > labels.txt
          Priority: Critical|ff2222|Critical, needs to check quickly
          Priority: High|FF7922|Priority level high
          Priority: Medium|fbca04|Priority level medium
          Priority: Low|c2e0c6|Priority level low
          Status: Complete|7ED321|Task, feature, implemented without problems
          Status: Debugging|750DFF|Code debugging and searching errors on it
          Status: Feedback Needed|006b75|Feedback priority in some task, features, code…
          Status: Generate Conflicts|BB00B0|Feature that generates conflicts on code deployment
          Status: In Observation|00E1EA|Code implemented and feature is under observation in case generates conflicts
          Status: In Progress|FC8264|Still in progress or developing or checking functionality
          Status: On Discussion|8BFBFF|Feature or new function to implement, that need a little discussion over it
          Status: On Hold|BABABA|Task, feature is hold due to time or no people working there right now
          Status: Ready for Merge|34FF8D|Feature ready for merge and see functionality and how works
          Status: Ready for Test|007734|Feature confirmed and already finished, need some test before deploy on main branch
          Status: Review Needed|EAE435|Feature, task or code needs review for check the functionality
          Status: Stopped|000000|Currently functionality stopped
          Status: Under Consideration|B3B3B3|Developers thinking about the implementation of the feature, suggestion…
          Type: Bug|ff2222|Bug exists on code development, needs to check, review for fast push
          Type: Documentation|00858A|For code documentation issues or recomendation
          Type: Enhancement|1d76db|Enhancement for application that need to be review
          Type: Feature|6DFF6D|New feature to implement, need review
          Type: Help Needed|5319e7|Attention is needed
          Type: Idea|E6FF00|Idea, or suggestion for change some functionality on application
          Type: Question|FF6DD9|Question, for explain what exactly want to implement
          Type: Refactoring|00A7AE|Improvements for code, refactoring code on application
          Type: Regression|FF6B00|Suggestion for regression for an older version due to instability
          Type: Security|FF6767|Layer of security level, bug or zero day appears that compromise application functionality
          EOF

          while IFS='|' read -r name color desc; do
            gh label create "$name" \
              --color "$color" \
              --description "$desc" \
              --force
          done < labels.txt
